### PR TITLE
Added Raspberry Pi kinesis streaming example based on CDDBaseline

### PR DESCRIPTION
**Pull request by abroekhuis**
*Description of changes:*
Added an example for using Greengrass on a Raspberry Pi with Kinesis, for streaming with the Pi Camera to a Kinesis stream using GStreamer. Based on CDDBaseline.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by timmattison** [comment]
Taking a look now.

**Comment by timmattison** [comment]
Looking good. There are a few things I want to integrate into the config and update. But if I can get it working here this is going to be a great example for people. Thanks!

**Comment by timmattison** [comment]
Making great progress. Added an environment variable for the config, it fetches temporary credentials from Greengrass using the Greengrass role, and soon it'll locate the plugin if the user doesn't specify its location.

**Comment by timmattison** [comment]
I have it working really smoothly now. I did run into one case where there was no error printed but the stream didn't start. Trying to reproduce it so I can catch it and provide a clean error message.

**Comment by timmattison** [comment]
Figured out the issue. Will try to get this function in next week.

**Comment by abroekhuis** [comment]
I'm curious to the changes you did, can you share then already?

**Comment by timmattison** [comment]
Sure, merge commit is here - https://github.com/aws-samples/aws-greengrass-lambda-functions/commit/9759708494f4d8567648ad2871719f43a468ed14

The only issue is that the Kinesis permissions need to be added to the deployment configuration or the deployment defaults since I use the Greengrass core's role to get KVS credentials. I didn't add those because every other project would have to inherit them. I am working on a way to add permissions on a per function basis.

**Comment by timmattison** [comment]
Probably easier to see the changes in this commit - https://github.com/aws-samples/aws-greengrass-lambda-functions/commit/9c5f8d48c3fa1928d6d40b71fae6d9861cfe5801 - instead of the full merge. Let me know if you have questions.

**Pull request merged**
